import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { themePresets } from "@/config/theme-presets";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const presetMap = JSON.stringify(
  themePresets.reduce<Record<string, { light: string; lightFg: string; dark: string; darkFg: string }>>(
    (acc, p) => {
      acc[p.name] = {
        light: p.light.primary,
        lightFg: p.light.primaryForeground,
        dark: p.dark.primary,
        darkFg: p.dark.primaryForeground,
      };
      return acc;
    },
    {},
  ),
);

const initScript = `
(function() {
  try {
    var p = localStorage.getItem('theme-preset') || 'neutral';
    var r = localStorage.getItem('theme-radius');
    var map = ${presetMap};
    var d = document.documentElement;
    d.dataset.themePreset = p;
    if (r) d.style.setProperty('--radius', r + 'rem');
  } catch (e) {}
})();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <head>
        <Script id="theme-init" strategy="beforeInteractive">
          {initScript}
        </Script>
      </head>
      <body className="min-h-full flex flex-col">
        <ThemeProvider>
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
